### ISSUE TITLE
Developers: Registration with confirmation

### ISSUE THREAD

**Issue by cweiske** [superfeedr/subtome#82]
The developer docs at http://docs.subtome.com/developers/ show only a way to register an application without any user interaction.

I'd call this intrusive, so I'd like to have a solution that asks the user if he wants to register (and with which title) the application.

**Comment by julien51** [comment]
Well, that's kind of the point. One of the design decisions was to make this button do most of the work itself rather than expect the user to configure it.

For us, web folks, it makes sense to "register" things... while for most people this is completely counter-intuitive. Things should work out of the box for them. If they use MyFantasicReader™, when they visit your blog, they should just see MyFantasicReader™ as an option when they click the "Follow" button.

Now, as the docs say, if you want to make a specific flow for YourReader™, that's also very possible... You could very well, ask them if they want to register  YourReader™ on your site, and, if they do, then you load the `<iframe>` with the following `src`: `https://www.subtome.com/register-no-ui.html?name=<Name of your application>&url=<url of the subscription handler>`
